# Generated by Django 3.1.2 on 2020-11-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='insumo'),
        ),
    ]
