# Generated by Django 3.1.2 on 2020-10-30 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_galeria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name': 'Galeria'},
        ),
    ]
