# Generated by Django 3.1.2 on 2020-10-30 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201030_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name': 'Galeria'},
        ),
    ]
