# Generated by Django 3.1.2 on 2020-11-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_galeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(upload_to='galeria'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='imagen',
            field=models.ImageField(upload_to='slider'),
        ),
    ]
