# Generated by Django 3.1.2 on 2020-10-30 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201030_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galeria'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicio'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Slider', 'verbose_name_plural': 'Slider'},
        ),
    ]
