# Generated by Django 3.1.2 on 2020-11-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201110_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='opciones_consulta',
            new_name='motivo',
        ),
    ]
